### ISSUE TITLE
Automate the Raffle Process

### ISSUE THREAD

**Issue by GFLEMING133** [msoe-sse/msoe-sse.github.io#107]
## User Story
As an SSE meeting organizer, I would like a way to randomly generate a raffle winner based on a user's entries. User's entries are currently tracked via the google sheet file used by the eBoard (see the events/points page). If we could use this data and pipe it to a frontend (using the sse-web-api) that would be awesome. 
 Some ideas for raffle boards and what this might look like:
https://www.classtools.net/random-name-picker/ 
https://wheelofnames.com/

**Comment by andy-wojciechowski** [comment]
As of 3/1/20 the following changes still need to be made.

1. Add each name only once and made the spinner weighted toward people's point total's
2. It seems like there is a bug that the spinner won't spin with 1 entry left.

There might be some potential things I'm missing in #114 but I'm not sure.

**Comment by andy-wojciechowski** [comment]
Closing this as we did not run any raffles this year due to COVID. If the raffle gets revived by a future eboard this issue can be reopened.
