### ISSUE TITLE
Site Text is Blue in IE/Edge on First Hit

### ISSUE THREAD

**Issue by GFLEMING133** [msoe-sse/msoe-sse.github.io#112]
Our website shows up in blue in edge/IE the first time you hit the site:
![image](https://user-images.githubusercontent.com/32335233/65900489-be051f00-e37b-11e9-89d1-ddae419e2487.png)

Changing the theme fixes this, but because it's an issue on Edge I think it's something we should look at.

**Comment by rgeorgebu** [comment]
Fixed by #103 - no IE support (as per the official website guidelines)
