### ISSUE TITLE
Sub-Club Pages

### ISSUE THREAD

**Issue by msoe-sse-webmaster** [msoe-sse/msoe-sse.github.io#117]
Related to issue #101 , it would be nice if each sub club had a page of their own on the main website. Each page would be specialized to what each club wanted on their page. For example, for website club, we would simply list our times, the current webmaster, a link to the repository for the website, Other sub-clubs could create content as they saw fit.

As far as navigation goes, the plan is to replace the "repositories" master heading on the website with a "sub-clubs" master heading, which would have website, game dev and programming competition as sub-menus. 

----
So far, for each org, the following should be listed at a minimum:
* Purpose or summary of the club
* Current leader
* Meeting time, location and duration for the club
* Any relevant code repositories

**Comment by andy-wojciechowski** [comment]
This has been released. New subclub pages have been created and can be updated at anytime. The new pages are current available at.
- https://msoe-sse.github.io/subclubs/website
- https://msoe-sse.github.io/subclubs/competitiveprogramming
- https://msoe-sse.github.io/subclubs/gamedev

Or the following once msoe-sse.com gets fixed
- http://msoe-sse.com/subclubs/website
- http://msoe-sse.com/subclubs/competitiveprogramming
- http://msoe-sse.com/subclubs/gamedev
