### ISSUE TITLE
Events Committee Page

### ISSUE THREAD

**Issue by msoe-sse-webmaster** [msoe-sse/msoe-sse.github.io#121]
The current events coordinator for SSE recently introduced the idea of an events committee and is eager to involve students with the committee. That said, I think we should add two things to announce the forming of this committee:
1) A post with information on how to sign up
2) A page with a description of the committee, a link to the google form (or however members should sign up), the current members of the committee, and the current meeting place/time for the committee.

**Comment by andy-wojciechowski** [comment]
Closing this issue. The events committee has currently not been running since the 2019-2020 school year. If a future Events Coordinator revives this committee then this issue can be reopened.
