### ISSUE TITLE
Replicate post from 2019 about elections being open

### ISSUE THREAD

**Issue by stanglersm** [msoe-sse/msoe-sse.github.io#125]
It should be updated with the following new files

Nomination Form: https://docs.google.com/forms/d/1-c3-igAjEqvfQNoVP1CTpoR3zCzEhnLr4smmUwXRaOI/edit

Date & Time:
Friday, February 7th from 12-1pm in DH310
at our Week 8 General Meeting

Sorry this isn't a super formal issue - I didn't get the template in here by default and it seems like it would be overkill anyway.

**Comment by andy-wojciechowski** [comment]
@msoe-sse-webmaster This gave me an idea for a feature for the Post Editor which is the issue I mentioned above. I don't think it's a huge priority at the moment but it would be a nice to have. I think we should also keep this in mind for the SG editor as well.
