### ISSUE TITLE
Secure msoe sse site with a certificate (Let's encrypt?)

### ISSUE THREAD

**Issue by paul-rinaldi** [msoe-sse/msoe-sse.github.io#145]
![image](https://user-images.githubusercontent.com/9328123/86931101-54315700-c0fd-11ea-92d2-bf3f35582f8b.png)

**Comment by andy-wojciechowski** [comment]
We're aware of this issue and it's on our list of things to do. We also have an issue for this already which is #97 so I'm going to close this issue out in favor of that one.
