### ISSUE TITLE
Mobile: Logo overlaps "About" test on About page

### ISSUE THREAD

**Issue by sorianog** [msoe-sse/msoe-sse.github.io#18]
![Mobile Preview](https://user-images.githubusercontent.com/13261711/46984194-0a474880-d0b2-11e8-9ed0-ec2bd64b2735.png)

**Comment by GFLEMING133** [comment]
This should be fixed now:
![image](https://user-images.githubusercontent.com/32335233/48961098-9feab900-ef37-11e8-9007-743c3c90cc33.png)

**Comment by sorianog** [comment]
@ GFLEMING133 ooo what tool is this? 🤓

**Comment by GFLEMING133** [comment]
Just developer tools on Firefox--nothing super special :)

**Comment by sorianog** [comment]
Oh, well. Thanks!
