### ISSUE TITLE
Eboard bios - fix typos and inconsistent casing

### ISSUE THREAD

**Issue by stanglersm** [msoe-sse/msoe-sse.github.io#35]
The first few bios fit a consistent format, and the next few stray away a bit. There are a few typos.
The big thing is that the standing of each member and other details are inconsistently capitalized throughout the 8 bios.

- [ ] Adhere all to same format
- [ ] Match casing for similar words (like "Junior" and "Software Engineering")
- [ ] Fix typos

**Comment by GFLEMING133** [comment]
Hey Sabrina! Thanks for bringing these to our attention--we're doing what we can to improve the eBoard bios. A release shortly here should help some of these issues. We'll let you know when it goes out!

**Comment by GFLEMING133** [comment]
Hey there! My apologies on updating this ticket. This should be totally fixed now, but please let us know if you find something you want fixed.
