### ISSUE TITLE
Add a footer/chin to the bottom of every page

### ISSUE THREAD

**Issue by stanglersm** [msoe-sse/msoe-sse.github.io#39]
Something that anchors to the bottom of every page and has the following content:

"The Destination for Professional Software Engineers written by Society of Software Engineers"
Our full name: MSOE Society of Software Engineers
Contact: admin@msoe-sse.com
Slack (link or url?): ?

Some of this should be discussed among the website time, and then take some creative freedom!
That being said, a footer should probably be relatively simple, but simple is always hard to achieve. 

- [ ] Add the space for it to exist 
- [ ] Add the content

**Comment by GFLEMING133** [comment]
Hey Sabrina! We're actually working on that right now, and we'll let you know as soon as we're able to get our work into a pull request and released.

**Comment by GFLEMING133** [comment]
Hey there Sabrina! A few days ago we released a footer for the SSE page. Thoughts on how it looks or what you'd want added to it?

**Comment by stanglersm** [comment]
@GFLEMING133 This looks great! I love it!
