### ISSUE TITLE
Feedback form

### ISSUE THREAD

**Issue by stanglersm** [msoe-sse/msoe-sse.github.io#60]
Stakeholders fill out the following:
Feedback loop
Stakeholder Contact: Sabrina Stangler
Contact: slack

Stakeholder need:
To give students an outlet for feedback whenever they want - somewhere to point them. This could just be some kind of reference to our email like "Shoot any questions or concerns over to admin@msoe-sse.com"

Description of functionality/Use Case:
Just refer them to the email if they have questions or concerns or feedback. Then also give them the option to fill out a Google Form if they want
https://docs.google.com/forms/d/e/1FAIpQLScC7nLS5hUqQ7kG4U8o81r7aqWKP5JnLxXW8dEfclEpI96g5A/viewform?usp=sf_link

Priority: 5

The Development team fills out the following:
Implementation Approach:
<Describe the most appropriate course of implementation>

Risk Assessment:
<Indicate the nature of risk involved and the methods used to mitigate>

Stakeholders and development team joint section:
Both stakeholders and dev team must work in conjunction to fill out this section before the card can be moved to Ready for Work.

Wireframing/Visual Example (Optional, dependent on feature request):
<This section can include images, samples of the outcome, etc. Images can be add by using `![Alternate Text](Link to Image)>

Acceptance Criteria:
<Describe what needs to happen in order to consider the new feature complete.>

**Comment by GFLEMING133** [comment]
Hey there! Are we good to close this issue? Apologies for not following up sooner.
