### ISSUE TITLE
search form on archive page just goes to duckduckgo

### ISSUE THREAD

**Issue by slang800** [msoe-sse/msoe-sse.github.io#69]
DuckDuckGo is cool, but I expected the results to be limited to just things on msoe-sse dot com. For example, typing "programming" into the search form on [this](http://msoe-sse.com/archive/) page takes me here: https://duckduckgo.com/?sites=&k8=%23444444&k9=%23D51920&kt=h&q=programming&ia=web

... where the top results are from Wikipedia and have nothing to do with SSE.

**Comment by GFLEMING133** [comment]
Hey there Sean! Sorry for the loooong wait in getting back to you. We're halfway through a solution for this. First, we implemented a site-wide searchbar that's now on our homepage. That should sort through all of our website's content. 

We're figuring out how to address the archive search bar as a team, and we'll let you know when we figure out what to do with it.

**Comment by GFLEMING133** [comment]
Okay, so I talked with the team and we think the best idea going forward is just to plain delete the archives page and get rid of it. It's unnecessary to have in the first place, seeing as our org doesn't have that many posts on the site. Hopefully this addresses your concerns--and again, thanks for taking the time to bring up an issue!
