### ISSUE TITLE
Add Travis CI to the sse-web-api

### ISSUE THREAD

**Issue by msoe-sse-webmaster** [msoe-sse/msoe-sse.github.io#91]
The Travis CI can be used to ensure no silly mistakes are made. Seeing as tests exist in the sse-web-api (previously the sse-points-api) we should implement a Travis CI to prevent silly mistakes being made.

**Comment by andy-wojciechowski** [comment]
Closing this as this was done a while ago. You can view the travis build passing at the repo home here: https://github.com/msoe-sse/sse-web-api
