### ISSUE TITLE
Weird Page Title

### ISSUE THREAD

**Issue by GFLEMING133** [msoe-sse/msoe-sse.github.io#92]
Our page title is repetitive and looks like something a 5-year-old would write:
![image](https://user-images.githubusercontent.com/32335233/63895686-70307c00-c9b5-11e9-9cfb-2e2d446a8c8b.png)
Let's change our page title to appear simply as "MSOE-SSE."

**Comment by rgeorgebu** [comment]
done

**Comment by rgeorgebu** [comment]
this is a ux hotfix that's why it's going into master
