### ISSUE TITLE
Add Contact Information For EBoard Members

### ISSUE THREAD

**Issue by GFLEMING133** [msoe-sse/msoe-sse.github.io#95]
We would like to have contact information for our eBoard members displayed on the website, so our viewers can get in touch with the people they need to.
Here's what we have so far:

### Sabrina Stangler:tm:  
stanglersm@msoe.edu
Linkedin.com/in/sabrinastangler
Twitter: @sabrinastangler
### Seth Fenske  
fenskesd@msoe.edu
(262) 977-4026
linkedin.com/in/seth-fenske-ab2704150/
https://github.com/CreeperElement (Does this count as social media?)
Twitter: @SethFenske

### Errin Miller
millerec@msoe.edu
(262) 402-3000
https://www.linkedin.com/in/errin-miller-900179145/
### Nick Scharrer 
Emails:
1. nscharrer@gmail.com
2. scharrernf@msoe.edu
Cell: 262-777-0993
LinkedIn: https://www.linkedin.com/in/nscharrer/

### Grace Fleming
Email: flemingg@msoe.edu
Cell: 505-278-9952
LinkedIn: https://www.linkedin.com/in/gracefleming/

### Kiel Dowdle
email: dowdlek@msoe.edu
phone: 414-313-6727
LinkedIn: https://www.linkedin.com/in/kieldowdle/

**Comment by andy-wojciechowski** [comment]
@GFLEMING133 unassigned this from myself so that a freshman can take this issue
